######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 14 21:00:42 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . trash
INCLUDEPATH += .

# Input
HEADERS += defs.h localmap.h mapmaker.h worldspace.h worldtree.h trash/defs.h
SOURCES += localmap.cpp main.cpp mapmaker.cpp worldspace.cpp worldtree.cpp
