######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 25 20:19:17 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += localmap.h worldspace.h worldtree.h
SOURCES += localmap.cpp main.cpp worldspace.cpp worldtree.cpp
