######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 1 23:28:13 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += defs.h localmap.h mapmaker.h worldspace.h worldtree.h
SOURCES += localmap.cpp main.cpp mapmaker.cpp worldspace.cpp worldtree.cpp
