######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 23 19:49:45 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += localmap.h worldspace.h worldtree.h
SOURCES += localmap.cpp main.cpp worldspace.cpp worldtree.cpp
